### ISSUE TITLE
may be a typo

### ISSUE THREAD

**Issue by ghost** [GrosSacASac/JavaScript-Set-Up#1]
https://github.com/GrosSacASac/JavaScript-Set-Up/blob/master/js/Object.js#L8 Object.create(Object.prototype)

**Comment by GrosSacASac** [comment]
Yes I made a mistake thanks for pointing that out.
Object.create(Object) is almost the same as Object.create(Object.prototype), and the differences are hard to observe because Object.create(Object) creates an Object whose proto is the Object function which itself as any function in JS , has down the line the Object.prototype as proto. Which means that the usual prototype chain is not broken and Object.create(Object).hasOwnProperty() and co will just work. It also means that functions are also Objects. (but we already knew that)

**Comment by ghost** [comment]
:thumbsup:
